# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-AU

reviews:
  profile: chill
  request_changes_workflow: false
  poem: false
  path_filters:
    - "!**/bin/**"
    - "!**/obj/**"
  auto_review:
    enabled: true
    drafts: false
  tools:
    gitleaks:
      enabled: false
    semgrep:
      enabled: false
